### ISSUE TITLE
加载模型预训练权重报错

### ISSUE THREAD

**Issue by Sunnycl** [649453932/Bert-Chinese-Text-Classification-Pytorch#174]
报错信息：
Traceback (most recent call last):
  File "/baykal/public/zhangmeiyu/bert/run.py", line 39, in <module>
    model = x.Model(config).to(config.device)
  File "/baykal/public/zhangmeiyu/bert/models/bert.py", line 39, in __init__
    self.bert = BertModel.from_pretrained(config.bert_path)
  File "/baykal/public/zhangmeiyu/bert/pytorch_pretrained/modeling.py", line 604, in from_pretrained
    state_dict = torch.load(weights_path)
  File "/data/anaconda/envs/ability/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data/anaconda/envs/ability/lib/python3.8/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: storage has wrong byte size: expected %ld got %ld09437184
操作：
按照readme文档下载好bert_pertrain中需要的三个文件后运行python run.py --model bert时出现报错

**Comment by Cindycm** [comment]
解决了吗，怎么解决的
