### ISSUE TITLE
No such file or directory: 'THUCNews/saved_dict/bert.ckpt'

### ISSUE THREAD

**Issue by temco** [649453932/Bert-Chinese-Text-Classification-Pytorch#18]
按照流程clone项目，下载bert预训练集与vocab装入对应目录，运行run.py，抛出如下错误，请问如何修改？

```
python3 run.py --model bert   
Loading data...
180000it [00:28, 6288.85it/s]
10000it [00:01, 6258.25it/s]
10000it [00:01, 6435.75it/s]
Time usage: 0:00:32
Epoch [1/3]
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    train(config, model, train_iter, dev_iter, test_iter)
  File "/Users/temco/Downloads/Bert-Chinese-Text-Classification-Pytorch-master/train_eval.py", line 65, in train
    torch.save(model.state_dict(), config.save_path)
  File "/Users/temco/Library/Python/3.7/lib/python/site-packages/torch/serialization.py", line 260, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/temco/Library/Python/3.7/lib/python/site-packages/torch/serialization.py", line 183, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'THUCNews/saved_dict/bert.ckpt'
```

**Comment by daonna** [comment]
在THUCNews文件夹下新建文件夹saved_dict
