### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by Cgetier520990** [649453932/Bert-Chinese-Text-Classification-Pytorch#198]
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    train_data, dev_data, test_data = build_dataset(config)
  File "D:\PYTHON_PROGRAMME\Bert-Chinese-Text-Classification\utils.py", line 36, in build_dataset
    train = load_dataset(config.train_path, config.pad_size)
  File "D:\PYTHON_PROGRAMME\Bert-Chinese-Text-Classification\utils.py", line 20, in load_dataset
    token = config.tokenizer.tokenize(content)
AttributeError: 'NoneType' object has no attribute 'tokenize'
这个报错怎么解决？

**Comment by wangling6666** [comment]
我也出现这个错误，你解决了吗

**Comment by Cgetier520990** [comment]
没有诶，你现在解决了吗？

**Comment by CNMBE** [comment]
@wangling6666 @Cgetier520990 
我刚刚拉完代码也有这个问题，从huggingface把vocab.txt下载后放到模型文件夹就行

**Comment by TiezMind** [comment]
是因为从网上拉下来的文件名称不一致，要保证名称为vocab.txt并且在bert_pretrian的目录下
