### ISSUE TITLE
我写了一个predict

### ISSUE THREAD

**Issue by LydiaLXH** [649453932/Bert-Chinese-Text-Classification-Pytorch#28]
![image](https://user-images.githubusercontent.com/23496251/76505086-d2e5f280-6483-11ea-80e3-500e70f0e07a.png)

Connected to pydev debugger (build 181.4668.75)
打印texts：
(tensor([[ 101,  872, 1962, 1435,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0],
        [ 101,  872, 1962, 1004,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]]), tensor([4, 4]), tensor([[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]))
Traceback (most recent call last):
  File "D:\Software\pycharm\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Software\pycharm\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Software\pycharm\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Software\pycharm\PyCharm 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Program/Python/bert_classification_pytorch/predict_bak.py", line 48, in <module>
    label = bert_model.predict(test_demo)
  File "D:/Program/Python/bert_classification_pytorch/predict_bak.py", line 37, in predict
    outputs = self.model(texts)
  File "D:\Program\Python\bert_classification_pytorch\venv\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program\Python\bert_classification_pytorch\models\bert.py", line 42, in forward
    mask = x[2]  # 对padding部分进行mask，和句子一个size，padding部分用0表示，如：[1, 1, 1, 1, 0, 0]
IndexError: tuple index out of range

我这是哪里出错了呢？模型没有动过……
请各位大佬帮忙看下，非常感谢~

**Comment by RFHzhj** [comment]
你好，你的predict实现了吗？我想请教一下该怎么写

**Comment by LydiaLXH** [comment]
直接调用写好的evaluate方法就可以了
outputs, index = evaluate(self.config, self.model, content_iter)


单句测试要把class DatasetIterater(object)里的self.residue = True


| |
李璇
|
|
lydia_lxh@126.com
|
签名由网易邮箱大师定制


在2020年04月2日 17:01，RFHzhj<notifications@github.com> 写道：

你好，你的predict实现了吗？我想请教一下该怎么写

**Comment by LydiaLXH** [comment]
> 你好，你的predict实现了吗？我想请教一下该怎么写

直接调用写好的evaluate方法就可以了
outputs, index = evaluate(self.config, self.model, content_iter)

单句测试要把class DatasetIterater(object)里的self.residue = True

**Comment by LydiaLXH** [comment]
> 你好，你的predict实现了吗？我想请教一下该怎么写
直接调用写好的evaluate方法就可以了
单句测试要把class DatasetIterater(object)里的self.residue = True

**Comment by fxd75076162** [comment]
你好，我的predict也出现了你这个问题，请问你是如何解决的
