### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_pretrained_bert'

### ISSUE THREAD

**Issue by Inspiring26** [649453932/Bert-Chinese-Text-Classification-Pytorch#9]
# python3 run.py --model bert
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from train_eval import train, init_network
  File "/models/Bert-Chinese-Text-Classification-Pytorch/train_eval.py", line 9, in <module>
    from pytorch_pretrained_bert.optimization import BertAdam
ModuleNotFoundError: No module named 'pytorch_pretrained_bert'

train_eval.py依然需要pytorch_pretrained_bert

**Comment by Spr1nt0a0** [comment]
pip  install

**Comment by 595448755** [comment]
打开train_eval.py
将第9行，  from pytorch_pretrained_bert.optimization import BertAdam
改成：
from pytorch_pretrained.optimization import BertAdam
